// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message
type GetProductDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailRequest) Reset() {
	*x = GetProductDetailRequest{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailRequest) ProtoMessage() {}

func (x *GetProductDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailRequest.ProtoReflect.Descriptor instead.
func (*GetProductDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductDetailRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// Response message
type GetProductDetailResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images          []string               `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price           uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock           uint32                 `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	FinalPrice      uint64                 `protobuf:"varint,7,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	DiscountPercent uint32                 `protobuf:"varint,8,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	MinimumPurchase uint32                 `protobuf:"varint,9,opt,name=minimum_purchase,json=minimumPurchase,proto3" json:"minimum_purchase,omitempty"`
	MaximumPurchase *uint32                `protobuf:"varint,10,opt,name=maximum_purchase,json=maximumPurchase,proto3,oneof" json:"maximum_purchase,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProductDetailResponse) Reset() {
	*x = GetProductDetailResponse{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailResponse) ProtoMessage() {}

func (x *GetProductDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailResponse.ProtoReflect.Descriptor instead.
func (*GetProductDetailResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductDetailResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductDetailResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GetProductDetailResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductDetailResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GetProductDetailResponse) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GetProductDetailResponse) GetFinalPrice() uint64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *GetProductDetailResponse) GetDiscountPercent() uint32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *GetProductDetailResponse) GetMinimumPurchase() uint32 {
	if x != nil {
		return x.MinimumPurchase
	}
	return 0
}

func (x *GetProductDetailResponse) GetMaximumPurchase() uint32 {
	if x != nil && x.MaximumPurchase != nil {
		return *x.MaximumPurchase
	}
	return 0
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\aproduct\"8\n" +
	"\x17GetProductDetailRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\xe0\x02\n" +
	"\x18GetProductDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06images\x18\x03 \x03(\tR\x06images\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\rR\x05stock\x12\x1f\n" +
	"\vfinal_price\x18\a \x01(\x04R\n" +
	"finalPrice\x12)\n" +
	"\x10discount_percent\x18\b \x01(\rR\x0fdiscountPercent\x12)\n" +
	"\x10minimum_purchase\x18\t \x01(\rR\x0fminimumPurchase\x12.\n" +
	"\x10maximum_purchase\x18\n" +
	" \x01(\rH\x00R\x0fmaximumPurchase\x88\x01\x01B\x13\n" +
	"\x11_maximum_purchase2i\n" +
	"\x0eProductService\x12W\n" +
	"\x10GetProductDetail\x12 .product.GetProductDetailRequest\x1a!.product.GetProductDetailResponseB\x1fZ\x1dproduct-service/proto/productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_product_product_proto_goTypes = []any{
	(*GetProductDetailRequest)(nil),  // 0: product.GetProductDetailRequest
	(*GetProductDetailResponse)(nil), // 1: product.GetProductDetailResponse
}
var file_proto_product_product_proto_depIdxs = []int32{
	0, // 0: product.ProductService.GetProductDetail:input_type -> product.GetProductDetailRequest
	1, // 1: product.ProductService.GetProductDetail:output_type -> product.GetProductDetailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	file_proto_product_product_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
