// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build wireinject
// +build wireinject

package main

import (
	"order-service/internal/infra"
	"order-service/internal/repositories/datastore/orders"
	"order-service/internal/services"
	"order-service/internal/services/order"

	"github.com/google/wire"
)

func LoadServices() (*services.Service, func(), error) {
	wire.Build(
		infra.NewMysql,
		infra.ProvideTx,

		// REPOSITORY DATASTORE LAYER
		orders.SetWire,

		// SERVICE LAYER
		order.SetWire,

		services.NewService,
	)
	return nil, nil, nil
}
