// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build wireinject
// +build wireinject

package main

import (
	"cart-service/internal/config"
	"cart-service/internal/infra"
	"cart-service/internal/presentations/middleware"
	"cart-service/internal/repositories/datastore/carts"
	"cart-service/internal/repositories/datastore/products"
	"cart-service/internal/services"
	"cart-service/internal/services/cart"
	"cart-service/internal/utils"

	"github.com/google/wire"
)

func LoadServices() (*services.Service, *middleware.Middleware, func(), error) {
	wire.Build(
		infra.NewMysql,
		carts.NewCartRepository,
		products.NewProductRepository,
		infra.ProvideTx,
		wire.Struct(new(cart.OptionParams),
			"CartRepositoryReader",
			"CartRepositoryWriter",
			"ProductRepositoryReader",
			"Tx",
		),
		cart.New,
		services.NewService,
		config.NewRedisClient,
		utils.NewTokenUtil,
		middleware.NewMiddleware,
	)
	return nil, nil, nil, nil
}
