// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build wireinject
// +build wireinject

package main

import (
	"cart-service/internal/infra"
	"cart-service/internal/repositories/datastore/carts"
	grpcProduct "cart-service/internal/repositories/grpc/product"
	"cart-service/internal/services"
	"cart-service/internal/services/cart"

	"github.com/google/wire"
)

func LoadServices() (*services.Service, func(), error) {
	wire.Build(
		infra.NewMysql,
		infra.NewProductClient,
		infra.ProvideTx,

		// REPOSITORY DATASTORE LAYER
		carts.SetWire,
		grpcProduct.SetWire,

		// SERVICE LAYER
		cart.SetWire,

		services.NewService,
	)
	return nil, nil, nil
}
