openapi: 3.0.1
info:
  title: E-Commerce-API API
  version: 1.0.0
  description: |-
    - whatever it is in the form of an rfc3339 time response from be, using timezone utc. unless there is a specific field noted. but by default UTC
    - Note: When integrating with API, please read the field descriptions (request body, query params, query path, response body) on each endpoint
servers:
  - url: 'http://localhost:8080'
paths:
  '/v1/users/{userID}/carts/{productID}/increment':
    delete:
      operationId: ApiV1PatchIncrementCart
      summary: Increment total product in cart
      parameters:
        - name: userID
          in: path
          description: Id User
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
        - name: productID
          in: path
          description: Id Product
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
      responses:
        '200':
          description: Increment Product In Cart Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV1PatchIncrementCartResponseBody'
        '204':
          description: 'no content, berhasil dikirim'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '408':
          $ref: '#/components/responses/Timeout'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Cart
  '/v1/users/{userID}/carts/{productID}/decrement':
    delete:
      operationId: ApiV1PatchDecrementCart
      summary: Decrement total product in cart
      parameters:
        - name: userID
          in: path
          description: Id User
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
        - name: productID
          in: path
          description: Id Product
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
      responses:
        '200':
          description: Decrement Product In Cart Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV1PatchDecrementCartResponseBody'
        '204':
          description: 'no content, berhasil dikirim'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '408':
          $ref: '#/components/responses/Timeout'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Cart
  '/v1/users/{userID}/products/{productID}':
    delete:
      operationId: ApiV1DeleteCart
      summary: Delete product in cart
      parameters:
        - name: userID
          in: path
          description: Id User
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
        - name: productID
          in: path
          description: Id Product
          required: true
          schema:
            type: integer
            format: uint64
            example: 1
      responses:
        '200':
          description: Delete product in cart successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV1DeleteCartResponseBody'
        '204':
          description: 'no content, berhasil dikirim'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '408':
          $ref: '#/components/responses/Timeout'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Cart
  /v1/cart:
    post:
      operationId: ApiV1PostCart
      summary: Add product to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiV1PostCartRequestBody'
      responses:
        '200':
          description: Add product to cart successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiV1PostCartResponseBody'
        '204':
          description: 'no content, berhasil dikirim'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '408':
          $ref: '#/components/responses/Timeout'
        '500':
          $ref: '#/components/responses/InternalServerError'
      tags:
        - Cart
components:
  schemas:
    ApiV1DeleteCartResponseBody:
      type: object
      properties:
        message:
          description: Response Successfully
          type: string
          example: Delete product in cart Successfully
      required:
        - message
    ApiV1PostCartResponseBody:
      type: object
      properties:
        message:
          description: Response Successfully
          type: string
          example: Add product to cart Successfully
      required:
        - message
    ApiV1PostCartRequestBody:
      type: object
      properties:
        user_id:
          type: integer
          format: uint64
          example: 1
        product_id:
          type: integer
          format: uint64
          example: 1
        quantity:
          type: integer
          format: uint8
          example: 1
      required:
        - user_id
        - product_id
        - quantity
    ApiV1PatchIncrementCartResponseBody:
      type: object
      properties:
        message:
          description: Response Successfully
          type: string
          example: Increment product in cart Successfully
      required:
        - message
    ApiV1PatchDecrementCartResponseBody:
      type: object
      properties:
        message:
          description: Response Successfully
          type: string
          example: Decrement product in cart Successfully
      required:
        - message
    MetaDataOnlyPagination:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - pagination
    ErrorValidate:
      type: object
      properties:
        field:
          type: string
          example: email
        message:
          type: array
          items:
            type: string
          example:
            - Email is invalid
            - Email is required
      required:
        - field
        - message
    Token:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        expires_in:
          type: integer
          format: int32
          example: 3600
        expired_at:
          description: |
            - format: RFC3339
            - timezone: UTC
          type: string
          format: date-time
          example: '2023-10-01T12:00:00Z'
        token_type:
          type: string
          example: Bearer
      required:
        - token
        - expires_in
        - token_type
        - expired_at
    GeneralErrorResponse:
      type: object
      properties:
        data:
          description: 'Data is null if there is no data, must be null if there is an error'
          type: object
          nullable: true
        metadata:
          description: 'Metadata is null if there is no metadata, must be null if there is an error'
          type: object
          nullable: true
        message:
          description: Error message
          type: string
          example: Validation failed
        error_validations:
          type: array
          items:
            $ref: '#/components/schemas/ErrorValidate'
          example:
            - field: email
              message:
                - Email is invalid
          nullable: false
      required:
        - message
    MetaData:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - pagination
    Pagination:
      type: object
      properties:
        total:
          type: integer
          format: int64
          example: 100
        page:
          type: integer
          format: int64
          example: 1
        page_size:
          type: integer
          format: int64
          example: 10
        total_page:
          type: integer
          format: int64
          example: 10
      required:
        - total
        - page
        - page_size
        - total_page
  parameters:
    page:
      name: page
      in: query
      description: Page number for pagination
      required: true
      schema:
        type: integer
        format: int64
        example: 1
    page_size:
      name: page_size
      in: query
      description: Number of items per page for pagination
      required: true
      schema:
        type: integer
        format: int64
        example: 10
    search:
      name: search
      in: query
      description: Search term for filtering results
      required: false
      schema:
        type: string
        example: role_name
    sort_direction:
      name: sort_direction
      in: query
      description: Sort direction for the results
      required: true
      schema:
        type: string
        example: asc
        enum:
          - asc
          - desc
    sort_field:
      name: sort_field
      in: query
      description: Field to sort the results by
      required: true
      schema:
        type: string
        example: name
        enum:
          - name
          - id
  responses:
    Timeout:
      description: Timeout error
      content:
        application/json:
          schema:
            properties:
              message:
                description: Error message
                type: string
                example: Validation failed
            required:
              - message
    ResponseIDNumber:
      description: Response with ID
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
                example: 1
            required:
              - id
    UnauthorizedError:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    ForbiddenError:
      description: Forbidden access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    ValidationError:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
    BadRequest:
      description: Validation failed
      content:
        application/json:
          schema:
            properties:
              message:
                description: Error message
                type: string
                example: Validation failed
              error_validations:
                type: array
                items:
                  $ref: '#/components/schemas/ErrorValidate'
                example:
                  - field: email
                    message:
                      - Email is invalid
                nullable: false
            required:
              - message
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralErrorResponse'
  securitySchemes:
    AuthHeader:
      type: apiKey
      in: header
      name: Authorization
